version: 0.2

phases:
  build:
    commands:
      - echo test github cloud
      - echo test VPC and adding NAT EIP to allow list
      - printenv CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_EVENT
      - t="good"
      - |
        if [ expr "${CODEBUILD_WEBHOOK_BASE_REF}" = "PULL_REQUEST_CREATED" ] && [ "$t" = "good" ]; then
          echo helloworld
        else
          echo Something Wrong
#           exit 1
        fi
      - echo after test
      - ls
#       - sh test.sh
